### ISSUE TITLE
Accessing Credentials post authentication

### ISSUE THREAD

**Issue by esjmb** [scan/yesod-auth-oauth2#22]
Hi,

new to haskell, have read code though and cannot work this out - apologies if a dumb question, but I note in Github.hs there is a function fetchGithubProfile that gathers a useful set of details (eg. access_token) that one would want to access following authentication. However, tracing through the code, it appears to me that these are not stored away in Yesod.Auth.setCredsRedirect, which seems to just uses the definition of getAuthId to extract a single credential value for the user identifier, that is set in the _ID session key. It appears that the full set of creds obtained are never stored/accessible post authentication.

1) is this correct?
2) could a callback be added to the flow to enable such details to be retained (eg. stored to sb/session)
3) alternatively could the full set of credentials obtained be passed to a session variable (perhaps _ID_CREDS) encoded in JSON forma or equivalent?

It seems to me that the access_token is as important as choosing a credential as an id? For example, the most natural post authentication landing would be a registration completion page that would use these details.

thanks,
Stephen.

**Comment by pbrisbin** [comment]
You can see [here](https://github.com/scan/yesod-auth-oauth2/blob/master/Yesod/Auth/OAuth2/Github.hs#L118) that some of that information is included in the `credsExtra` field of the `Creds` value.

The idea is that when you login a new user through this flow, you grab these values and put them somewhere for your own use (like the DB). You can see an example of this [here](https://github.com/thoughtbot/carnival/blob/master/Foundation.hs#L150).

Does that meet your needs (I see `access_token` is there)?

**Comment by esjmb** [comment]
Hi pbrisbin,

yes that solves my problem. so I use the getAuthId function in the YesodAuth instance to process the Creds data passed to it. If I understand correctly the builder function pattern matches against a Creds' components, enabling it to then access the csExtra elements. 

sweet! :)

appreciate your time.

**Comment by pbrisbin** [comment]
> so I use the getAuthId function in the YesodAuth instance to process the Creds data passed to it

Just to be clear, you *define* the `getAuthId` function. Its job is to take a `Creds` and build/store a `User` before returning their `UserId`. Within its implementation, since you have a `Creds`, you can use its `credsExtra` value for whatever you need.

> If I understand correctly the builder function pattern matches against a Creds' components, enabling it to then access the csExtra elements

Yup, that's what we're doing -- though that's just one way to do things. Here are some docs that may help: 

- http://hackage.haskell.org/package/yesod-auth-1.4.2/docs/Yesod-Auth.html#v:getAuthId
- http://hackage.haskell.org/package/yesod-auth-1.4.2/docs/Yesod-Auth.html#v:Creds

**Comment by esjmb** [comment]
Hi Pat,

yes thanks. So, here is an example of a simple getAuthId I defined to put the access_token to the session.

getAuthId cr@(Creds csPlugin csIdent csExtra) = do
    let access_token = lookup "access_token" csExtra
    case access_token of
        Just token -> setSession "access_token" token
        _ -> deleteSession "access_token"
    return . Just . credsIdent $ cr

appreciate not the most beautiful code :)

thanks for your help.
