### ISSUE TITLE
Support `state` to prevent CSRF

### ISSUE THREAD

**Issue by jprider63** [scan/yesod-auth-oauth2#23]
Hi,

I was wondering if you'd be interesting in adding support for the `state` field to prevent CSRF attacks. I think you'd just need to modify the callback dispatch like `oauth2GithubScoped` does. 

JP

**Comment by pbrisbin** [comment]
I don't know a ton about this. Generally, if adding something makes things safer and doesn't require anything from existing or new end-users of the library, then I don't see why not.

**Comment by jprider63** [comment]
I took a shot at this here: d33cc46b87a9efce5421cc076b1b243363fe8b72

The main compatibility issue I see is when plugins manually set the state (like Github). I think it should be relatively painless to change these though.

**Comment by pbrisbin** [comment]
The diff looks reasonable enough to me. Would you like to move it to a proper PR and pickup discussion/review there?
